### ISSUE TITLE
Compatible with ES6?

### ISSUE THREAD

**Issue by tconroy** [hurrymaplelad/sinon-codemod#2]
Hey there,
trying to run `extract-calls-fake` on some test files written in ES6, however it seems to just skip over the files...

```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 2.245seconds
```

Was wondering if this was ES6 compatible?

**Comment by hurrymaplelad** [comment]
Hrm, the parsing is all done by [recast](https://github.com/benjamn/recast), so I suspect it's compatible, though I haven't tested it exhaustively.

A code sample that's not getting transformed would be super helpful.

This codemod hasn't seen a ton of use yet, so it likely has some holes.

**Comment by dvdzkwsk** [comment]
Seeing the same here, none of the files get modified. Fairly new to jscodeshift, so I'll do some digging.

**Comment by ghost** [comment]
This codemod is definitely compatible with ES2015+. I have run it on a very large project that uses much of that syntax. That said, there were a few patterns it did not catch. See #7  for the details. If you can test your project against that branch that would be helpful too.

**Comment by hurrymaplelad** [comment]
Testa are using some es6 syntax.
