### ISSUE TITLE
wont work with a getter or setter

### ISSUE THREAD

**Issue by shaunc** [hurrymaplelad/sinon-codemod#3]
Won't properly replace expressions like:

    sinon.stub(obj, "prop", {get: fakeGetter, set: fakeSetter})

With

    sinon.stub(obj, "prop").get(fakeGetter).set(fakeSetter)

I'm not sure this case can be fully detected syntactically, as the get, set hash could be passed in....

**Comment by azu** [comment]
Same problem.
This transform script convert  
```js
    sinon.stub(person, 'isWork', {
      get() {
        return true;
      }
    })
```

to 

```js
    sinon.stub(person, 'isWork').callsFake({
      get() {
        return true;
      }
    })
```

The converted code fail test.
