### ISSUE TITLE
this._sandbox in mocha tests is not overwritten

### ISSUE THREAD

**Issue by ghost** [hurrymaplelad/sinon-codemod#5]
Our mocha tests use this pattern:
```javascript
before(function() {
	this._sandbox = sinon.sandbox.create();
});
it('does something', function() {
	const confirm = this._sandbox.stub(window, 'confirm', () => false);
});
```

https://github.com/hurrymaplelad/sinon-codemod/blob/master/extract-calls-fake.js#L7 currently just matches `sinon.stub`. Would be nice to have this codemod handle the above sandbox the pattern. I am tinkering now with the options to see if I can add support.

**Comment by hurrymaplelad** [comment]
Thanks for the report and the fix in #7!
